### ISSUE TITLE
Missing page content

### ISSUE THREAD

**Issue by enamchae** [ArnavKaushik/stogarobotics#5]
Opening this as the submission deadline draws closer.

## Todo

- Remaining member icons. Additional team gallery images, if desired.

## Challenge specifications

From the [Robot Events challenge page](http://challenges.robotevents.com/challenge/106):

> The Robotics Team Website Challenge sponsored by Dell is a challenge asking you to develop a website that promotes your entire robotics program. This may include:
>
> * Your VEX IQ Challenge, VEX Robotics Competition, or VEX U team(s),
> * Other robotics programs in which you participate,
> * Outreach/mentoring activities,
> * Your Past/Present/Future (what you have done, who you are, where you are, and what you plan to do in the future),
> * And how to join.
> 
> In short, build a website that tells the world how great is youth robotics and how special is your program. You are encouraged to promote all the STEM activities in which your robotics program participates (VRC, BEST, Botball, FIRST, TSA, PLTW, SKILLS USA, SKILLS Canada, underwater robotics, workshops, camps, math competitions, bridge building, solar-powered cars, etc.)

> * **Bonus points** provided for a website that provides recognition for sponsors, teachers, mentors, and schools.

> Judges evaluate websites with these questions in mind:
> 
> * How well does the website tell the story of the program?
> * Does it provide information for outsiders wanting to learn about your program?
> * Is the website attractive and easy to navigate and does it have a unified design?
> * Does the website have a clear, easy-to-use layout, good structure, and consistent use of colors, menus, and imagery?
> * Does it include outreach activities, who you are, where you are, what you have done, and your plans?

## Previous winners

Provided for reference…

(Old sites may have been updated since previous seasons.)

### [2019 winners](https://www.roboticseducation.org/robotics-education-competition-foundation-2019-online-challenge-winners-announced/)

1. [356 - The Dragons](https://www.team356.ca/) ([Submission page](https://challenges.robotevents.com/challenge/95/entry/5883))
2. [254 - FIRST](https://www.team254.com/about/) ([Submission page](https://challenges.robotevents.com/challenge/95/entry/6290))
3. [7784 & 8931 - Viking Colt](https://www.cbots-vbots.club/) ([Submission page](https://challenges.robotevents.com/challenge/95/entry/5595))

### [2018 winner](https://www.roboticseducation.org/robotics-education-competition-foundation-2018-online-challenge-winners-announced-2/)

1. [4104 - North Hardin](https://northhardin4104.wixsite.com/nhhsvexrobotics) ([Submission page](https://challenges.robotevents.com/challenge/81/entry/4160))

### [2017 winners](https://www.vexforum.com/t/2017-online-challenge-winners/40563)

1. 8931 - Viking Colt (Unavailable) ([Submission page](http://challenges.robotevents.com/challenge/66/entry/2757))
2. [Robotics Association at UWM](https://www.roboticsuwm.com/) ([Submission page](http://challenges.robotevents.com/challenge/66/entry/3648))
3. [2919 - K-Force](http://kforce.org.nz/) ([Submission page](http://challenges.robotevents.com/challenge/66/entry/2937))

**Comment by ArnavKaushik** [comment]
More content added to spreadsheets, and more Bitmojis have been added to the Drive folder. Please update whenever you get a chance. Also, any members without a role should be assigned "Team Member". Thanks!
